export interface FeatureOption {
  value: string;
  label: string;
}

export const REQUIRED_FEATURES: Record<string, FeatureOption[]> = {
  TRM: [
    { value: 'TRM_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TRM_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TRM_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TRM_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TRM_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TRM_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TRM_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TRM_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TRM_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TRM_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TRM_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TRM_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TRM_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TRM_TRM_ACC_DEATH', label: 'Life cover accidental death benefit' },
    { value: 'TRM_TRM_FUNERAL', label: 'Life cover funeral expenses benefit' },
    { value: 'TRM_TRM_TERM_ILL', label: 'Life cover terminal illness benefit' },
    { value: 'TRM_TRM_INJURY', label: 'Life cover severe trauma benefit' },
    { value: 'TRM_TRM_CHILD', label: 'Life cover complimentary child insurance' },
    { value: 'TRM_TRM_COUNSEL', label: 'Life cover counselling benefit' },
    { value: 'TRM_TRM_LOYAL', label: 'Life cover loyalty benefit' },
    { value: 'TRM_TRM_PREM_HOL', label: 'Life cover premium and cover suspension' },
    { value: 'TRM_TRM_CONVERT', label: 'Life cover conversion options' },
  ],
  TPE: [
    { value: 'TPE_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TPE_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TPE_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TPE_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TPE_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TPE_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TPE_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TPE_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TPE_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TPE_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TPE_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TPE_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TPE_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TPE_TPD_ANY_AVAIL', label: 'TPD Any occupation available' },
    { value: 'TPE_TPD_OWN_AVAIL', label: 'TPD Own occupation available' },
    { value: 'TPE_TPD_PPD', label: 'TPD partial and permanent disability benefit' },
    { value: 'TPE_TPD_DEATH', label: 'TPD death benefit' },
    { value: 'TPE_TPD_ACCOMM', label: 'TPD accommodation benefit' },
    { value: 'TPE_TPD_CHILD', label: 'TPD complimentary child insurance' },
    { value: 'TPE_TPD_COUNSEL', label: 'TPD counselling benefit' },
    { value: 'TPE_TPD_LOYAL', label: 'TPD loyalty benefit' },
    { value: 'TPE_TPD_BB', label: 'Life Buy Back after TPD' },
    { value: 'TPE_TPD_DTPD', label: 'Double TPD' },
    { value: 'TPE_TPD_PREM_HOL', label: 'TPD premium and cover suspension' },
    { value: 'TPE_TPD_CONVERT', label: 'TPD cover conversion options' },
  ],
  TRE: [
    { value: 'TRE_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TRE_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TRE_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TRE_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TRE_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TRE_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TRE_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TRE_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TRE_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TRE_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TRE_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TRE_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TRE_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TRE_TRA_DEATH', label: 'Trauma death benefit' },
    { value: 'TRE_TRA_ACCOMM', label: 'Trauma accommodation benefit' },
    { value: 'TRE_TRA_CHILD', label: 'Trauma complimentary child insurance' },
    { value: 'TRE_TRA_INTENSE_CR', label: 'Trauma intensive care benefit' },
    { value: 'TRE_TRA_COUNSEL', label: 'Trauma counselling benefit' },
    { value: 'TRE_TRA_LOYAL', label: 'Trauma loyalty benefit' },
    { value: 'TRE_TRA_ALZHEIMERS', label: "Alzheimer's disease and dementias" },
    { value: 'TRE_TRA_AORTIC_SUR', label: 'Aortic surgery' },
    { value: 'TRE_TRA_APLASTC_AN', label: 'Aplastic anaemia' },
    { value: 'TRE_TRA_BRAIN_TUMR', label: 'Benign Brain tumour' },
    { value: 'TRE_TRA_C_ORGAN', label: 'Cancer' },
    { value: 'TRE_TRA_C_LEUK', label: 'Cancer - Leukaemia' },
    { value: 'TRE_TRA_C_MEL', label: 'Cancer - Melanoma' },
    { value: 'TRE_TRA_C_PROSTATE', label: 'Cancer - Prostate' },
    { value: 'TRE_TRA_C_BREAST', label: 'Carcinoma in situ - Breast' },
    { value: 'TRE_TRA_C_CERVIX', label: 'Carcinoma in situ - Cervix' },
    { value: 'TRE_TRA_C_FALLOP', label: 'Carcinoma in situ - Fallopian Tube' },
    { value: 'TRE_TRA_C_OVARY', label: 'Carcinoma in situ - Ovary' },
    { value: 'TRE_TRA_C_PENIS', label: 'Carcinoma in situ - Penis' },
    { value: 'TRE_TRA_C_PERI', label: 'Carcinoma in situ - Perineum' },
    { value: 'TRE_TRA_C_TESTICLE', label: 'Carcinoma in situ - Testicle' },
    { value: 'TRE_TRA_C_UTERUS', label: 'Carcinoma in situ - Uterus' },
    { value: 'TRE_TRA_C_VAGINA', label: 'Carcinoma in situ - Vagina' },
    { value: 'TRE_TRA_C_VULVA', label: 'Carcinoma in situ - Vulva' },
    { value: 'TRE_TRA_COLITIS', label: 'Severe Ulcerative Colitis' },
    { value: 'TRE_TRA_COLOSTOMY', label: 'Colostomy and/or ileostomy' },
    { value: 'TRE_TRA_COMA', label: 'Coma' },
    { value: 'TRE_TRA_CROHN', label: "Severe Crohn's Disease" },
    { value: 'TRE_TRA_DIABETES', label: 'Diabetes type 1' },
    { value: 'TRE_TRA_ENCEPHALTS', label: 'Encephalitis / Meningitis' },
    { value: 'TRE_TRA_ENDO', label: 'Endometriosis' },
    { value: 'TRE_TRA_FACE', label: 'Facial reconstruction' },
    { value: 'TRE_TRA_HEART_CARD', label: 'Heart - Cardiomyopathy' },
    { value: 'TRE_TRA_HEART_ANG', label: 'Heart - Coronary Artery Angioplasty' },
    { value: 'TRE_TRA_HEART_ATV', label: 'Heart - Coronary Artery Angioplasty Triple Vessel' },
    { value: 'TRE_TRA_HEART_BYP', label: 'Heart - Coronary Artery By-Pass' },
    { value: 'TRE_TRA_HEART_ATT', label: 'Heart - Heart Attack' },
    { value: 'TRE_TRA_HEART_VAL', label: 'Heart - Heart Valve Surgery' },
    { value: 'TRE_TRA_HEART_SUR', label: 'Heart - Open Heart Surgery' },
    { value: 'TRE_TRA_HEART_CA', label: 'Heart - Out of Hospital Cardiac Arrest' },
    { value: 'TRE_TRA_HIV_AIDS', label: 'HIV medically acquired' },
    { value: 'TRE_TRA_C_MOLE', label: 'Hydatidiform mole' },
    { value: 'TRE_TRA_HYDRO', label: 'Hydrocephalus' },
    { value: 'TRE_TRA_KIDNY_FAIL', label: 'Kidney failure' },
    { value: 'TRE_TRA_LIVER_DIS', label: 'Liver disease' },
    { value: 'TRE_TRA_LOSS_HEAR', label: 'Loss of hearing' },
    { value: 'TRE_TRA_LOSS_INDEP', label: 'Loss of independence' },
    { value: 'TRE_TRA_LOSS_LIMBS', label: 'Loss of limbs' },
    { value: 'TRE_TRA_LOSS_SIGHT', label: 'Loss of sight' },
    { value: 'TRE_TRA_LOSS_SPECH', label: 'Loss of speech' },
    { value: 'TRE_TRA_LUNG_DIS', label: 'Lung disease' },
    { value: 'TRE_TRA_LUPUS', label: 'Lupus' },
    { value: 'TRE_TRA_MAJOR_HEAD', label: 'Major head trauma' },
    { value: 'TRE_TRA_ORGAN_TRAN', label: 'Major organ transplant' },
    { value: 'TRE_TRA_MOTOR_NEUR', label: 'Motor neurone disease' },
    { value: 'TRE_TRA_MULT_SCLER', label: 'Multiple sclerosis' },
    { value: 'TRE_TRA_MUSC_DYSTR', label: 'Muscular dystrophy' },
    { value: 'TRE_TRA_OSTEO', label: 'Severe Osteoporosis' },
    { value: 'TRE_TRA_PARALYSIS', label: 'Paralysis' },
    { value: 'TRE_TRA_PARKINSONS', label: "Parkinson's disease" },
    { value: 'TRE_TRA_NEURO', label: 'Peripheral Neuropathy' },
    { value: 'TRE_TRA_PNEUM', label: 'Pneumonectomy' },
    { value: 'TRE_TRA_PREG', label: 'Pregnancy complications' },
    { value: 'TRE_TRA_HYPERTENSN', label: 'Pulmonary hypertension' },
    { value: 'TRE_TRA_ARTHRITIS', label: 'Rheumatoid arthritis' },
    { value: 'TRE_TRA_SEV_BURNS', label: 'Severe burns' },
    { value: 'TRE_TRA_SDIABETES', label: 'Severe diabetes' },
    { value: 'TRE_TRA_STROKE', label: 'Stroke' },
    { value: 'TRE_TRA_TRABB', label: 'Trauma reinstatement' },
    { value: 'TRE_TRA_PREM_HOL', label: 'Trauma premium and cover suspension' },
    { value: 'TRE_TRA_CONVERT', label: 'Trauma cover conversion options' },
  ],
  TPS: [
    { value: 'TPS_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TPS_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TPS_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TPS_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TPS_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TPS_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TPS_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TPS_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TPS_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TPS_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TPS_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TPS_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TPS_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TPS_TPD_ANY_AVAIL', label: 'TPD Any occupation available' },
    { value: 'TPS_TPD_OWN_AVAIL', label: 'TPD Own occupation available' },
    { value: 'TPS_TPD_PPD', label: 'TPD partial and permanent disability benefit' },
    { value: 'TPS_TPD_DEATH', label: 'TPD death benefit' },
    { value: 'TPS_TPD_ACCOMM', label: 'TPD accommodation benefit' },
    { value: 'TPS_TPD_CHILD', label: 'TPD complimentary child insurance' },
    { value: 'TPS_TPD_COUNSEL', label: 'TPD counselling benefit' },
    { value: 'TPS_TPD_LOYAL', label: 'TPD loyalty benefit' },
    { value: 'TPS_TPD_BB', label: 'Life Buy Back after TPD' },
    { value: 'TPS_TPD_DTPD', label: 'Double TPD' },
    { value: 'TPS_TPD_PREM_HOL', label: 'TPD premium and cover suspension' },
    { value: 'TPS_TPD_CONVERT', label: 'TPD cover conversion options' },
  ],
  TRS: [
    { value: 'TRS_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TRS_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TRS_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TRS_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TRS_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TRS_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TRS_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TRS_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TRS_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TRS_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TRS_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TRS_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TRS_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TRS_TRA_DEATH', label: 'Trauma death benefit' },
    { value: 'TRS_TRA_ACCOMM', label: 'Trauma accommodation benefit' },
    { value: 'TRS_TRA_CHILD', label: 'Trauma complimentary child insurance' },
    { value: 'TRS_TRA_INTENSE_CR', label: 'Trauma intensive care benefit' },
    { value: 'TRS_TRA_COUNSEL', label: 'Trauma counselling benefit' },
    { value: 'TRS_TRA_LOYAL', label: 'Trauma loyalty benefit' },
    { value: 'TRS_TRA_ALZHEIMERS', label: "Alzheimer's disease and dementias" },
    { value: 'TRS_TRA_AORTIC_SUR', label: 'Aortic surgery' },
    { value: 'TRS_TRA_APLASTC_AN', label: 'Aplastic anaemia' },
    { value: 'TRS_TRA_BRAIN_TUMR', label: 'Benign Brain tumour' },
    { value: 'TRS_TRA_C_ORGAN', label: 'Cancer' },
    { value: 'TRS_TRA_C_LEUK', label: 'Cancer - Leukaemia' },
    { value: 'TRS_TRA_C_MEL', label: 'Cancer - Melanoma' },
    { value: 'TRS_TRA_C_PROSTATE', label: 'Cancer - Prostate' },
    { value: 'TRS_TRA_C_BREAST', label: 'Carcinoma in situ - Breast' },
    { value: 'TRS_TRA_C_CERVIX', label: 'Carcinoma in situ - Cervix' },
    { value: 'TRS_TRA_C_FALLOP', label: 'Carcinoma in situ - Fallopian Tube' },
    { value: 'TRS_TRA_C_OVARY', label: 'Carcinoma in situ - Ovary' },
    { value: 'TRS_TRA_C_PENIS', label: 'Carcinoma in situ - Penis' },
    { value: 'TRS_TRA_C_PERI', label: 'Carcinoma in situ - Perineum' },
    { value: 'TRS_TRA_C_TESTICLE', label: 'Carcinoma in situ - Testicle' },
    { value: 'TRS_TRA_C_UTERUS', label: 'Carcinoma in situ - Uterus' },
    { value: 'TRS_TRA_C_VAGINA', label: 'Carcinoma in situ - Vagina' },
    { value: 'TRS_TRA_C_VULVA', label: 'Carcinoma in situ - Vulva' },
    { value: 'TRS_TRA_COLITIS', label: 'Severe Ulcerative Colitis' },
    { value: 'TRS_TRA_COLOSTOMY', label: 'Colostomy and/or ileostomy' },
    { value: 'TRS_TRA_COMA', label: 'Coma' },
    { value: 'TRS_TRA_CROHN', label: "Severe Crohn's Disease" },
    { value: 'TRS_TRA_DIABETES', label: 'Diabetes type 1' },
    { value: 'TRS_TRA_ENCEPHALTS', label: 'Encephalitis / Meningitis' },
    { value: 'TRS_TRA_ENDO', label: 'Endometriosis' },
    { value: 'TRS_TRA_FACE', label: 'Facial reconstruction' },
    { value: 'TRS_TRA_HEART_CARD', label: 'Heart - Cardiomyopathy' },
    { value: 'TRS_TRA_HEART_ANG', label: 'Heart - Coronary Artery Angioplasty' },
    { value: 'TRS_TRA_HEART_ATV', label: 'Heart - Coronary Artery Angioplasty Triple Vessel' },
    { value: 'TRS_TRA_HEART_BYP', label: 'Heart - Coronary Artery By-Pass' },
    { value: 'TRS_TRA_HEART_ATT', label: 'Heart - Heart Attack' },
    { value: 'TRS_TRA_HEART_VAL', label: 'Heart - Heart Valve Surgery' },
    { value: 'TRS_TRA_HEART_SUR', label: 'Heart - Open Heart Surgery' },
    { value: 'TRS_TRA_HEART_CA', label: 'Heart - Out of Hospital Cardiac Arrest' },
    { value: 'TRS_TRA_HIV_AIDS', label: 'HIV medically acquired' },
    { value: 'TRS_TRA_C_MOLE', label: 'Hydatidiform mole' },
    { value: 'TRS_TRA_HYDRO', label: 'Hydrocephalus' },
    { value: 'TRS_TRA_KIDNY_FAIL', label: 'Kidney failure' },
    { value: 'TRS_TRA_LIVER_DIS', label: 'Liver disease' },
    { value: 'TRS_TRA_LOSS_HEAR', label: 'Loss of hearing' },
    { value: 'TRS_TRA_LOSS_INDEP', label: 'Loss of independence' },
    { value: 'TRS_TRA_LOSS_LIMBS', label: 'Loss of limbs' },
    { value: 'TRS_TRA_LOSS_SIGHT', label: 'Loss of sight' },
    { value: 'TRS_TRA_LOSS_SPECH', label: 'Loss of speech' },
    { value: 'TRS_TRA_LUNG_DIS', label: 'Lung disease' },
    { value: 'TRS_TRA_LUPUS', label: 'Lupus' },
    { value: 'TRS_TRA_MAJOR_HEAD', label: 'Major head trauma' },
    { value: 'TRS_TRA_ORGAN_TRAN', label: 'Major organ transplant' },
    { value: 'TRS_TRA_MOTOR_NEUR', label: 'Motor neurone disease' },
    { value: 'TRS_TRA_MULT_SCLER', label: 'Multiple sclerosis' },
    { value: 'TRS_TRA_MUSC_DYSTR', label: 'Muscular dystrophy' },
    { value: 'TRS_TRA_OSTEO', label: 'Severe Osteoporosis' },
    { value: 'TRS_TRA_PARALYSIS', label: 'Paralysis' },
    { value: 'TRS_TRA_PARKINSONS', label: "Parkinson's disease" },
    { value: 'TRS_TRA_NEURO', label: 'Peripheral Neuropathy' },
    { value: 'TRS_TRA_PNEUM', label: 'Pneumonectomy' },
    { value: 'TRS_TRA_PREG', label: 'Pregnancy complications' },
    { value: 'TRS_TRA_HYPERTENSN', label: 'Pulmonary hypertension' },
    { value: 'TRS_TRA_ARTHRITIS', label: 'Rheumatoid arthritis' },
    { value: 'TRS_TRA_SEV_BURNS', label: 'Severe burns' },
    { value: 'TRS_TRA_SDIABETES', label: 'Severe diabetes' },
    { value: 'TRS_TRA_STROKE', label: 'Stroke' },
    { value: 'TRS_TRA_TRABB', label: 'Trauma reinstatement' },
    { value: 'TRS_TRA_PREM_HOL', label: 'Trauma premium and cover suspension' },
    { value: 'TRS_TRA_CONVERT', label: 'Trauma cover conversion options' },
  ],
  TPR: [
    { value: 'TPR_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'TPR_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'TPR_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'TPR_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'TPR_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'TPR_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'TPR_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'TPR_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'TPR_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'TPR_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'TPR_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'TPR_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'TPR_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'TPR_TPD_ANY_AVAIL', label: 'TPD Any occupation available' },
    { value: 'TPR_TPD_OWN_AVAIL', label: 'TPD Own occupation available' },
    { value: 'TPR_TPD_PPD', label: 'TPD partial and permanent disability benefit' },
    { value: 'TPR_TPD_DEATH', label: 'TPD death benefit' },
    { value: 'TPR_TPD_ACCOMM', label: 'TPD accommodation benefit' },
    { value: 'TPR_TPD_CHILD', label: 'TPD complimentary child insurance' },
    { value: 'TPR_TPD_COUNSEL', label: 'TPD counselling benefit' },
    { value: 'TPR_TPD_LOYAL', label: 'TPD loyalty benefit' },
    { value: 'TPR_TPD_BB', label: 'Life Buy Back after TPD' },
    { value: 'TPR_TPD_DTPD', label: 'Double TPD' },
    { value: 'TPR_TPD_PREM_HOL', label: 'TPD premium and cover suspension' },
    { value: 'TPR_TPD_CONVERT', label: 'TPD cover conversion options' },
  ],
  INC: [
    { value: 'INC_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'INC_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'INC_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'INC_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'INC_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'INC_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'INC_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'INC_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'INC_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'INC_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'INC_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'INC_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'INC_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'INC_INC_AGREED', label: 'Income Protection agreed value' },
    { value: 'INC_INC_INDEMN', label: 'Income Protection indemnity option' },
    { value: 'INC_INC_OWN', label: 'Availability of own occupation beyond 2 years of benefit' },
    { value: 'INC_INC_TOT_DISAB', label: 'Total disability benefit - IP - best occupation definition' },
    { value: 'INC_INC_TOT_DISABB', label: 'Total disability benefit - IP - worst occupation definition' },
    { value: 'INC_INC_PART_DISAB', label: 'Partial disability benefit - IP - best occupation definition' },
    { value: 'INC_INC_PART_DISABB', label: 'Partial disability benefit - IP - worst occupation definition' },
    { value: 'INC_INC_DEATH_BEN', label: 'IP death benefit' },
    { value: 'INC_INC_SEVERE_DIS', label: 'IP severe disability benefit' },
    { value: 'INC_INC_BOOST', label: 'IP booster benefit' },
    { value: 'INC_INC_SPECIFIC_INJURY', label: 'IP specific injury benefit' },
    { value: 'INC_INC_CRISIS_BEN', label: 'IP crisis benefit' },
    { value: 'INC_INC_ELECT_SURG', label: 'IP elective surgery benefit' },
    { value: 'INC_INC_ABO', label: 'IP accident benefit option' },
    { value: 'INC_INC_BED_BEN', label: 'IP waiting period bed benefit' },
    { value: 'INC_INC_ACCOMMODATION', label: 'IP accommodation benefit' },
    { value: 'INC_INC_TRANS_BEN', label: 'IP transportation benefit' },
    { value: 'INC_INC_NURSE', label: 'IP home care benefit' },
    { value: 'INC_INC_CHILD_CARE', label: 'IP child care benefit' },
    { value: 'INC_INC_REHAB_BEN', label: 'IP rehabilitation benefits' },
    { value: 'INC_INC_RET_WORK', label: 'IP return to work bonus' },
    { value: 'INC_INC_NO_CLAIM', label: 'IP no claim discount / bonuses' },
    { value: 'INC_INC_ICB', label: 'IP increasing claim benefit' },
    { value: 'INC_INC_LUMP_SUM', label: 'IP lump sum benefit' },
    { value: 'INC_INC_COUNSEL', label: 'IP counselling benefit' },
    { value: 'INC_INC_CHILD', label: 'IP complimentary child insurance' },
    { value: 'INC_INC_LOYAL', label: 'IP loyalty benefit' },
    { value: 'INC_INC_SUPER_CONTRIB', label: 'IP superannuation contribution option' },
    { value: 'INC_INC_COVER_UNEM', label: 'IP cover whilst unemployed' },
    { value: 'INC_INC_WAIT_CHANGE', label: 'IP waiting period conversion' },
    { value: 'INC_INC_RECUR_DIS', label: 'IP recurrent disability' },
    { value: 'INC_INC_COVER_EXT', label: 'IP cover extension' },
    { value: 'INC_INC_PREM_HOL', label: 'IP premium and cover suspension' },
  ],
  BUS: [
    { value: 'BUS_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'BUS_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'BUS_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'BUS_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'BUS_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'BUS_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'BUS_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'BUS_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'BUS_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'BUS_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'BUS_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'BUS_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'BUS_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'BUS_BUS_TOT_DISAB', label: 'BE total disability benefit' },
    { value: 'BUS_BUS_PART_DISAB', label: 'BE partial disability benefit' },
    { value: 'BUS_BUS_DEATH_BEN', label: 'BE death benefit' },
    { value: 'BUS_BUS_CRISIS_BEN', label: 'BE crisis benefit' },
    { value: 'BUS_BUS_ELECT_SURG', label: 'BE elective surgery benefit' },
    { value: 'BUS_BUS_ABO', label: 'BE accident benefit option' },
    { value: 'BUS_BUS_TRANS_BEN', label: 'BE transportation benefit' },
    { value: 'BUS_BUS_NO_CLAIM', label: 'BE no claim discount / bonuses' },
    { value: 'BUS_BUS_LOYAL', label: 'BE loyalty benefit' },
    { value: 'BUS_BUS_RECUR_DIS', label: 'BE recurrent disability' },
    { value: 'BUS_BUS_BEN_EXTEN', label: 'BE benefit extension' },
    { value: 'BUS_BUS_COVER_EXT', label: 'BE cover extension' },
    { value: 'BUS_BUS_PREM_HOL', label: 'BE premium and cover suspension' },
  ],
  NES: [
    { value: 'NES_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'NES_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'NES_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'NES_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'NES_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'NES_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'NES_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'NES_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'NES_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'NES_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'NES_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'NES_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'NES_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'NES_NES_DES', label: 'Occupational HIV or Hepatitis cover' },
  ],
  CHT: [
    { value: 'CHT_ALL_STEP_PREM', label: 'Variable age-stepped premiums' },
    { value: 'CHT_ALL_LEVEL_PREM', label: 'Variable premiums' },
    { value: 'CHT_ALL_HEALTH', label: 'Healthy lives discounts and benefits' },
    { value: 'CHT_ALL_FINPLANNING', label: 'Financial planning benefit' },
    { value: 'CHT_ALL_WAIVE_PREM', label: 'Premium waiver on disability' },
    { value: 'CHT_ALL_GTEED_UPGRADE', label: 'Guarantee of upgrade' },
    { value: 'CHT_ALL_GTEED_RENEW', label: 'Guaranteed renewable' },
    { value: 'CHT_ALL_GTEED_RATE', label: 'Guarantee of premium rates' },
    { value: 'CHT_ALL_GTEED_INS', label: 'Future insurability' },
    { value: 'CHT_ALL_BUS_INS', label: 'Business future insurability' },
    { value: 'CHT_ALL_INDEXATION', label: 'Benefit indexation' },
    { value: 'CHT_ALL_PREM_FREEZ', label: 'Premium freeze option' },
    { value: 'CHT_ALL_WORLD_COV', label: 'Worldwide cover' },
    { value: 'CHT_CHT_CONT', label: 'Child trauma cover continuation if the parent cover ends' },
    { value: 'CHT_CHT_CONV_TRM', label: 'Child trauma cover convertable to a life plan' },
    { value: 'CHT_CHT_CONV_TRA', label: 'Child trauma cover convertable to a trauma plan' },
    { value: 'CHT_CHT_ACCOM', label: 'Child trauma accommodation benefit' },
    { value: 'CHT_CHT_COUNSEL', label: 'Child trauma grief counselling' },
    { value: 'CHT_CHT_INDEX', label: 'Child trauma indexation' },
    { value: 'CHT_CHT_GFI', label: 'Child trauma cover increases' },
    { value: 'CHT_CHT_PARTIAL', label: 'Child trauma partial payments' },
  ],
};

export function stripNeedPrefix(needCode: string, featureValue: string): string {
  const prefix = `${needCode}_`;
  return featureValue.startsWith(prefix) ? featureValue.slice(prefix.length) : featureValue;
}
