export interface FeatureOption {
  value: string;
  label: string;
}

export const REQUIRED_FEATURES: Record<string, FeatureOption[]> = {
  TRM: [
    { value: 'TRM_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TRM_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TRM_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TRM_ALL_TERM', label: 'Term' },
    { value: 'TRM_ALL_WOL', label: 'Whole of Life' },
    { value: 'TRM_ALL_FUNERAL', label: 'Funeral' },
    { value: 'TRM_ALL_ACCIDENTAL_DEATH', label: 'Accidental Death' },
    { value: 'TRM_ALL_TERMINAL_ILLNESS', label: 'Terminal Illness' },
    { value: 'TRM_ALL_LIVING_BENEFIT', label: 'Living Benefit' },
    { value: 'TRM_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TRM_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TRM_ALL_NEEDLESTICK', label: 'Needlestick' },
    { value: 'TRM_ALL_GRIEF_SUPPORT', label: 'Grief Support' },
    { value: 'TRM_ALL_BEST_DOCTORS', label: 'Best Doctors' },
    { value: 'TRM_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  TPE: [
    { value: 'TPE_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TPE_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TPE_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TPE_ALL_ANY_OCC', label: 'Any Occupation' },
    { value: 'TPE_ALL_OWN_OCC', label: 'Own Occupation' },
    { value: 'TPE_ALL_HOME_MAKER', label: 'Home Maker' },
    { value: 'TPE_ALL_NON_WORKING', label: 'Non Working' },
    { value: 'TPE_ALL_BUY_BACK', label: 'Buy Back' },
    { value: 'TPE_ALL_DOUBLE_TPD', label: 'Double TPD' },
    { value: 'TPE_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TPE_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TPE_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  TRE: [
    { value: 'TRE_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TRE_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TRE_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TRE_ALL_BUY_BACK', label: 'Buy Back' },
    { value: 'TRE_ALL_DOUBLE_TRAUMA', label: 'Double Trauma' },
    { value: 'TRE_ALL_TRAUMA_REINSTATEMENT', label: 'Trauma Reinstatement' },
    { value: 'TRE_ALL_CHILD_TRAUMA', label: 'Child Trauma' },
    { value: 'TRE_ALL_BABY_CARE', label: 'Baby Care' },
    { value: 'TRE_ALL_PREGNANCY_COMPS', label: 'Pregnancy Complications' },
    { value: 'TRE_ALL_BEST_DOCTORS', label: 'Best Doctors' },
    { value: 'TRE_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TRE_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TRE_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  TPS: [
    { value: 'TPS_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TPS_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TPS_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TPS_ALL_ANY_OCC', label: 'Any Occupation' },
    { value: 'TPS_ALL_OWN_OCC', label: 'Own Occupation' },
    { value: 'TPS_ALL_HOME_MAKER', label: 'Home Maker' },
    { value: 'TPS_ALL_NON_WORKING', label: 'Non Working' },
    { value: 'TPS_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TPS_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TPS_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  TRS: [
    { value: 'TRS_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TRS_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TRS_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TRS_ALL_TRAUMA_REINSTATEMENT', label: 'Trauma Reinstatement' },
    { value: 'TRS_ALL_CHILD_TRAUMA', label: 'Child Trauma' },
    { value: 'TRS_ALL_BABY_CARE', label: 'Baby Care' },
    { value: 'TRS_ALL_PREGNANCY_COMPS', label: 'Pregnancy Complications' },
    { value: 'TRS_ALL_BEST_DOCTORS', label: 'Best Doctors' },
    { value: 'TRS_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TRS_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TRS_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  TPR: [
    { value: 'TPR_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'TPR_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'TPR_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'TPR_ALL_ANY_OCC', label: 'Any Occupation' },
    { value: 'TPR_ALL_OWN_OCC', label: 'Own Occupation' },
    { value: 'TPR_ALL_BUY_BACK', label: 'Buy Back' },
    { value: 'TPR_ALL_DOUBLE_TPD', label: 'Double TPD' },
    { value: 'TPR_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'TPR_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'TPR_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  INC: [
    { value: 'INC_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'INC_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'INC_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'INC_ALL_AGREED_VALUE', label: 'Agreed Value' },
    { value: 'INC_ALL_INDEMNITY', label: 'Indemnity' },
    { value: 'INC_ALL_ACCIDENT_BENEFIT', label: 'Accident Benefit' },
    { value: 'INC_ALL_DAY_1_ACCIDENT', label: 'Day 1 Accident' },
    { value: 'INC_ALL_INCREASING_CLAIM', label: 'Increasing Claim' },
    { value: 'INC_ALL_BOOSTER_BENEFIT', label: 'Booster Benefit' },
    { value: 'INC_ALL_SUPER_CONTRIBUTION', label: 'Super Contribution' },
    { value: 'INC_ALL_TRAUMA_OPTION', label: 'Trauma Option' },
    { value: 'INC_ALL_SPECIFIC_INJURY', label: 'Specific Injury' },
    { value: 'INC_ALL_CRISIS_BENEFIT', label: 'Crisis Benefit' },
    { value: 'INC_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'INC_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
    { value: 'INC_ALL_BEST_DOCTORS', label: 'Best Doctors' },
    { value: 'INC_ALL_FUTURE_INSURABILITY', label: 'Future Insurability' },
  ],
  BUS: [
    { value: 'BUS_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'BUS_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'BUS_ALL_HYBRID_PREM', label: 'Hybrid Premium' },
    { value: 'BUS_ALL_AGREED_VALUE', label: 'Agreed Value' },
    { value: 'BUS_ALL_INDEMNITY', label: 'Indemnity' },
    { value: 'BUS_ALL_PREMIUM_FREEZE', label: 'Premium Freeze' },
    { value: 'BUS_ALL_PREMIUM_PAUSE', label: 'Premium Pause' },
  ],
  NES: [
    { value: 'NES_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'NES_ALL_LEVEL_PREM', label: 'Level Premium' },
  ],
  CHT: [
    { value: 'CHT_ALL_STEP_PREM', label: 'Stepped Premium' },
    { value: 'CHT_ALL_LEVEL_PREM', label: 'Level Premium' },
    { value: 'CHT_ALL_BABY_CARE', label: 'Baby Care' },
    { value: 'CHT_ALL_PREGNANCY_COMPS', label: 'Pregnancy Complications' },
  ],
};

export function stripNeedPrefix(needCode: string, featureValue: string): string {
  const prefix = `${needCode}_`;
  return featureValue.startsWith(prefix) ? featureValue.slice(prefix.length) : featureValue;
}
